version: '3'
services:
  db:
    image: mysql:8.0
    container_name: "spring_db"
    ports:
      - 3306:3306
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "forex_rate"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tokyo"

  spring:
    container_name: "spring_api"
    ports:
      - 9090:8080
    tty: true
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
