version: '3'
services:
  db:
    container_name: "mysql_db"
    build:
      context: .
      dockerfile: ./Database/Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./Database/init:/docker-entrypoint-initdb.d
      - ./Database/mysql.cnf:/etc/mysql/conf.d/my.cnf
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: amateras_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    networks:
      - backdb

  spring:
    container_name: "spring_api"
    ports:
      - 9090:8080
    tty: true
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/amateras_db?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      IS_DEBUG_MODE: ${IS_DEBUG_MODE:-true}
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    networks:
      - backdb
networks:
  backdb:
    driver: bridge
